// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjJjH3kbRNNU2ilJqz38U3Jizs7HGqUE',
    appId: '1:576447832285:web:91d3177f03ac8d4a643b34',
    messagingSenderId: '576447832285',
    projectId: 'dormdash-v3',
    authDomain: 'dormdash-v3.firebaseapp.com',
    storageBucket: 'dormdash-v3.firebasestorage.app',
    measurementId: 'G-NFE5ZRZM5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebKH1KEdFBWG9sEFBJrMfJMXtsUmorQY',
    appId: '1:576447832285:android:803c823240383646643b34',
    messagingSenderId: '576447832285',
    projectId: 'dormdash-v3',
    storageBucket: 'dormdash-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJ3Zt0XAGjwvECNpgw3QMvcKYjSVSGrw',
    appId: '1:576447832285:ios:2046087ec234d921643b34',
    messagingSenderId: '576447832285',
    projectId: 'dormdash-v3',
    storageBucket: 'dormdash-v3.firebasestorage.app',
    iosBundleId: 'com.github.team10M3Demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJ3Zt0XAGjwvECNpgw3QMvcKYjSVSGrw',
    appId: '1:576447832285:ios:01c6bc6707809377643b34',
    messagingSenderId: '576447832285',
    projectId: 'dormdash-v3',
    storageBucket: 'dormdash-v3.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkjJjH3kbRNNU2ilJqz38U3Jizs7HGqUE',
    appId: '1:576447832285:web:1dd75a7f838ef55a643b34',
    messagingSenderId: '576447832285',
    projectId: 'dormdash-v3',
    authDomain: 'dormdash-v3.firebaseapp.com',
    storageBucket: 'dormdash-v3.firebasestorage.app',
    measurementId: 'G-RQJ7BSQ4H5',
  );
}
