// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTwOlzZdn422HTA9ZHphuyAo1b1MSQd6U',
    appId: '1:365189879488:android:77cb171cf6413e7894bf25',
    messagingSenderId: '365189879488',
    projectId: 'dormdash-v2',
    storageBucket: 'dormdash-v2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClC4Np2Pzw3huhPWh9tckuiMV42e7DLpU',
    appId: '1:365189879488:web:665e7f30d3115c7c94bf25',
    messagingSenderId: '365189879488',
    projectId: 'dormdash-v2',
    authDomain: 'dormdash-v2.firebaseapp.com',
    storageBucket: 'dormdash-v2.firebasestorage.app',
    measurementId: 'G-1TPM5RW0CR',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClC4Np2Pzw3huhPWh9tckuiMV42e7DLpU',
    appId: '1:365189879488:web:1000ffcdfd8ee8c894bf25',
    messagingSenderId: '365189879488',
    projectId: 'dormdash-v2',
    authDomain: 'dormdash-v2.firebaseapp.com',
    storageBucket: 'dormdash-v2.firebasestorage.app',
    measurementId: 'G-MJRK94JZMJ',
  );

}